# Generated by Django 5.1.6 on 2025-02-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_make_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='type',
            field=models.CharField(max_length=10, unique=True, verbose_name='性別'),
        ),
    ]
