# Generated by Django 5.1.6 on 2025-02-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='line_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
