# Generated by Django 5.1.6 on 2025-03-08 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_line_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('train_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toilet.trainline')),
            ],
        ),
    ]
