# Generated by Django 5.1.6 on 2025-03-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_username'),
        ('toilet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationTicketGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_ticket_gate', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('toilet_stall', models.IntegerField(help_text='個室数を入力してください')),
                ('warm_water_washing_toilet_seat', models.BooleanField(null=True)),
                ('child_facility', models.BooleanField(null=True)),
                ('barrier_free_toilet', models.BooleanField(null=True)),
                ('wheelchair', models.BooleanField(null=True)),
                ('powder_room', models.BooleanField(null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender')),
            ],
        ),
        migrations.CreateModel(
            name='MaleToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('toilet_stall', models.IntegerField(help_text='個室数を入力してください')),
                ('urial', models.IntegerField(help_text='小便器数を入力してください')),
                ('warm_water_washing_toilet_seat', models.BooleanField(null=True)),
                ('child_facility', models.BooleanField(null=True)),
                ('barrier_free_toilet', models.BooleanField(null=True)),
                ('wheelchair', models.BooleanField(null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender')),
            ],
        ),
        migrations.CreateModel(
            name='MultiFunctionalToilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('toilet_stall', models.IntegerField(help_text='個室数を入力してください')),
                ('warm_water_washing_toilet_seat', models.BooleanField(null=True)),
                ('child_facility', models.BooleanField(null=True)),
                ('barrier_free_toilet', models.BooleanField(null=True)),
                ('wheelchair', models.BooleanField(null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('value', models.IntegerField(help_text='5段階で数値を入力してください')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toilet_female_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toilet.femaletoilet')),
                ('toilet_male_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toilet.maletoilet')),
                ('toilet_multifunctional_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toilet.multifunctionaltoilet')),
            ],
        ),
        migrations.CreateModel(
            name='ToiletMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('floor', models.CharField(help_text='設置されている階を数字で入力してください', max_length=5)),
                ('near_gate', models.CharField(max_length=100)),
                ('near_home_num', models.CharField(max_length=3)),
                ('near_train_door_num', models.CharField(max_length=3)),
                ('toilet_root', models.TextField(null=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.trainstation')),
                ('station_ticket_gate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toilet.stationticketgate')),
            ],
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='toilet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.toiletmaster'),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='toilet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.toiletmaster'),
        ),
        migrations.AddField(
            model_name='femaletoilet',
            name='toilet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.toiletmaster'),
        ),
    ]
