# Generated by Django 5.1.6 on 2025-03-29 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_username'),
        ('toilet', '0002_stationticketgate_femaletoilet_maletoilet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='toilet_female_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='toilet_male_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='toilet_multifunctional_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.gender'),
            preserve_default=False,
        ),
    ]
