# Generated by Django 5.1.6 on 2025-03-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0003_remove_comment_toilet_female_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toilet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='toilet.toiletmaster'),
            preserve_default=False,
        ),
    ]
