# Generated by Django 5.1.6 on 2025-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0004_comment_toilet'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaletoilet',
            name='congestion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='femaletoilet',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='congestion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='congestion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='size',
            field=models.FloatField(null=True),
        ),
    ]
