# Generated by Django 5.1.6 on 2025-04-08 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0006_comment_congestion_comment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='data_create',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='コメントされた日時'),
        ),
    ]
