# Generated by Django 5.1.6 on 2025-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0007_comment_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaletoilet',
            name='initial_congestion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='femaletoilet',
            name='initial_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='femaletoilet',
            name='initial_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='initial_congestion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='initial_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='initial_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='initial_congestion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='initial_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='initial_value',
            field=models.FloatField(null=True),
        ),
    ]
