# Generated by Django 5.1.6 on 2025-04-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0008_femaletoilet_initial_congestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainline',
            name='railway_company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
