# Generated by Django 5.1.6 on 2025-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0009_trainline_railway_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaletoilet',
            name='fitting_board',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='femaletoilet',
            name='full_length_mirror',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='femaletoilet',
            name='trash_can',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='fitting_board',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='full_length_mirror',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='trash_can',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='fitting_board',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='full_length_mirror',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='trash_can',
            field=models.BooleanField(null=True),
        ),
    ]
