# Generated by Django 5.1.6 on 2025-05-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0010_femaletoilet_fitting_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstation',
            name='station_name_japanese',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
