# Generated by Django 5.1.6 on 2025-05-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0011_trainstation_station_name_japanese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstation',
            name='station_name_japanese',
            field=models.CharField(max_length=255),
        ),
    ]
