# Generated by Django 5.1.6 on 2025-05-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0012_alter_trainstation_station_name_japanese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maletoilet',
            name='toilet_stall',
        ),
        migrations.CreateModel(
            name='ToiletStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('western_style', models.IntegerField(blank=True, null=True)),
                ('japanese_style', models.IntegerField(blank=True, null=True)),
                ('female_toilet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toilet.femaletoilet')),
                ('male_toilet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toilet.maletoilet')),
                ('multi_toilet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toilet.multifunctionaltoilet')),
            ],
        ),
    ]
