# Generated by Django 5.1.6 on 2025-05-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0013_remove_maletoilet_toilet_stall_toiletstall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='femaletoilet',
            name='toilet_stall',
        ),
        migrations.RemoveField(
            model_name='multifunctionaltoilet',
            name='toilet_stall',
        ),
    ]
