# Generated by Django 5.1.6 on 2025-05-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0014_remove_femaletoilet_toilet_stall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toiletmaster',
            old_name='near_train_door_num',
            new_name='near_train_car_num',
        ),
    ]
