# Generated by Django 5.2.1 on 2025-05-14 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_username'),
        ('toilet', '0015_rename_near_train_door_num_toiletmaster_near_train_car_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('value', models.IntegerField(help_text='5段階で数値を入力してください')),
                ('size', models.IntegerField(help_text='5段階で数値を入力してください', null=True)),
                ('congestion', models.IntegerField(help_text='5段階で数値を入力してください', null=True)),
                ('data_create', models.DateTimeField(default=django.utils.timezone.now, help_text='コメントされた日時')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.maletoilet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
