# Generated by Django 5.2.1 on 2025-05-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0017_rename_malecomments_maletoiletcomments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
