# Generated by Django 5.2.1 on 2025-05-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0018_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletmaster',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='toiletmaster',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
