# Generated by Django 5.2.1 on 2025-05-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0019_alter_toiletmaster_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletmaster',
            name='near_home_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='toiletmaster',
            name='near_train_car_num',
            field=models.CharField(max_length=30),
        ),
    ]
