# Generated by Django 5.2.1 on 2025-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0020_alter_toiletmaster_near_home_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toiletmaster',
            name='near_train_car_num',
            field=models.CharField(max_length=50),
        ),
    ]
