# Generated by Django 5.2.1 on 2025-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0021_alter_toiletmaster_near_train_car_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='maletoilet',
            name='powder_room',
            field=models.BooleanField(null=True),
        ),
    ]
