# Generated by Django 5.2.1 on 2025-05-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0022_maletoilet_powder_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='femaletoilet',
            name='child_seat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='maletoilet',
            name='child_seat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='multifunctionaltoilet',
            name='child_seat',
            field=models.BooleanField(null=True),
        ),
    ]
